# Generated by Django 3.1.1 on 2020-09-28 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(verbose_name='INCOME')),
                ('savings', models.FloatField(verbose_name='SAVINGS')),
                ('totalExpenditure', models.FloatField(verbose_name='TOTAL EXPENDITURE')),
                ('housing', models.FloatField(verbose_name='HOUSING')),
                ('food', models.FloatField(verbose_name='FOOD')),
                ('healthcare', models.FloatField(verbose_name='HEALTHCARE')),
                ('transportation', models.FloatField(verbose_name='TRANSPORTATION')),
                ('recreation', models.FloatField(verbose_name='RECREATION')),
                ('miscellaneous', models.FloatField(verbose_name='MISCELLANEOUS')),
                ('totalTransactions', models.IntegerField(verbose_name='TOTAL TRANSACTIONS')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(verbose_name='AMOUNT')),
                ('type', models.IntegerField(choices=[(0, 'Income'), (1, 'Housing'), (2, 'Food'), (3, 'Healthcare'), (4, 'Transportation'), (5, 'Recreation'), (6, 'Miscellaneous')], verbose_name='Type')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detail', verbose_name='DETAILS')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
        ),
    ]
