# Generated by Django 3.1.1 on 2020-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201001_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='income',
            field=models.FloatField(default=0, editable=0, verbose_name='INCOME'),
        ),
    ]
