# Generated by Django 3.1.1 on 2020-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201003_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default='No Description Provided!', verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Income'), (1, 'Housing'), (2, 'Food'), (3, 'Healthcare'), (4, 'Transportation'), (5, 'Recreation'), (6, 'Miscellaneous'), (7, 'Other')], verbose_name='Type'),
        ),
    ]
