# Generated by Django 3.1.1 on 2020-10-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201007_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.BooleanField(default=False, verbose_name='CREDIT'),
        ),
    ]
