# Generated by Django 3.1.1 on 2020-10-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201009_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detail', verbose_name='DETAILS'),
        ),
    ]
