# Generated by Django 3.1.1 on 2020-10-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201015_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='DATE CREATED'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='LAST UPDATED'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED'),
        ),
    ]
