# Generated by Django 3.1.1 on 2020-10-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201015_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='others',
            field=models.FloatField(default=0, verbose_name='OTHERS'),
        ),
        migrations.AddField(
            model_name='detail',
            name='stock',
            field=models.FloatField(default=0, verbose_name='STOCK'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Income'), (1, 'Housing'), (2, 'Food'), (3, 'Healthcare'), (4, 'Transportation'), (5, 'Recreation'), (6, 'Miscellaneous'), (7, 'Other'), (8, 'Stock')], verbose_name='Type'),
        ),
    ]
