# Generated by Django 3.1.1 on 2020-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201023_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='miscellaneous',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Income'), (1, 'Housing'), (2, 'Food'), (3, 'Healthcare'), (4, 'Transportation'), (5, 'Recreation'), (6, 'Other'), (7, 'Stock')], verbose_name='Type'),
        ),
    ]
