//login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//signup
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//Authenticate
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

//logout
export const LOG_OUT = "LOG_OUT";

//clear messages 
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";


//Forgot password
export const FORGOT_START = "FORGOT_START";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAILURE = "FORGOT_FAILURE";

//Switch tabs
export const SHOW_DETAILS_PAGE ="SHOW_DETAILS_PAGE";
export const SHOW_CHATBOT_PAGE ="SHOW_CHATBOT_PAGE";
export const VIEW_DETAILS ="VIEW_DETAILS";
export const SHOW_AMAZON_DETAILS ="SHOW_AMAZON_DETAILS";
export const SHOW_STOCK_DETAILS ="SHOW_STOCK_DETAILS";



//ADD Transactions
export const TRANSACTION_START = "TRANSACTION_START";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";

//Fetch Transactions
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_TRANSACTION_START = "FETCH_TRANSACTION_START";

//Update Transaction
export const UPDATE_BOX_SHOW = "UPDATE_BOX_SHOW";
export const UPDATE_SUCCESS_TRANSACTION = "UPDATE_TRANSACTION";
export const UPDATE_FAILURE_TRANSACTION="UPDATE_FAILURE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";



//delete transaction
export const DELETE_SUCCESS_TRANSACTION = "DELETE_SUCCESS_TRANSACTION";
export const DELETE_FAILURE_TRANSACTION = "DELETE_FAILURE_TRANSACTION";


//chat messages
export const DISPLAY_CHAT_MESSAGE = "DISPLAY_CHAT_MESSAGE";
export const ADD_CHAT_MESSAGE ="ADD_CHAT_MESSAGE";

//wishlist
export const SHOW_WISHLIST = "SHOW_WISHLIST";